stages:
  training:
    cmd: python script.py train
    deps:
    - script.py
    - utils/utils.py
    - var/holidays_events.csv
    - var/oil.csv
    - var/stores.csv
    - var/train.csv
    params:
    - utils/config.yml:
      - random_forest_parameters.n_estimators
      - random_forest_parameters.criterion
      - random_forest_parameters.max_depth
      - random_forest_parameters.min_samples_split
      - random_forest_parameters.min_samples_leaf
      - random_forest_parameters.min_weight_fraction_leaf
      - random_forest_parameters.max_features
      - random_forest_parameters.max_leaf_nodes
      - random_forest_parameters.min_impurity_decrease
      - random_forest_parameters.bootstrap
      - random_forest_parameters.oob_score
      - random_forest_parameters.n_jobs
      - random_forest_parameters.random_state
      - random_forest_parameters.verbose
      - random_forest_parameters.warm_start
      - random_forest_parameters.ccp_alpha
      - random_forest_parameters.max_samples
      - random_forest_parameters.monotonic_cst
    outs:
    - var/model.pkl
    metrics:
    - var/training_metrics.json
  inference:
    cmd: python script.py infer
    deps:
    - script.py
    - utils/utils.py
    - var/model.pkl
    outs:
    - submission.csv
